[2024-02-29T10:57:19.359+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-29T10:57:07.261430+00:00 [queued]>
[2024-02-29T10:57:19.385+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-29T10:57:07.261430+00:00 [queued]>
[2024-02-29T10:57:19.386+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-02-29T10:57:19.500+0000] {taskinstance.py:2214} INFO - Executing <Task(SnowflakeOperator): blob_to_snowflake_stg> on 2024-02-29 10:57:07.261430+00:00
[2024-02-29T10:57:19.511+0000] {standard_task_runner.py:60} INFO - Started process 1060 to run task
[2024-02-29T10:57:19.520+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'AIRLINES_ETL_PIPELINE', 'blob_to_snowflake_stg', 'manual__2024-02-29T10:57:07.261430+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/AIRLINES_DATA_ETL_DAG.py', '--cfg-path', '/tmp/tmplt_cg8sw']
[2024-02-29T10:57:19.531+0000] {standard_task_runner.py:88} INFO - Job 112: Subtask blob_to_snowflake_stg
[2024-02-29T10:57:20.600+0000] {task_command.py:423} INFO - Running <TaskInstance: AIRLINES_ETL_PIPELINE.blob_to_snowflake_stg manual__2024-02-29T10:57:07.261430+00:00 [running]> on host 586f09520b0e
[2024-02-29T10:57:21.440+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='AIRLINES_ETL_PIPELINE' AIRFLOW_CTX_TASK_ID='blob_to_snowflake_stg' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T10:57:07.261430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T10:57:07.261430+00:00'
[2024-02-29T10:57:21.442+0000] {sql.py:276} INFO - Executing: Truncat  table TEST_ANALYTICS.AIRLINES.airlines_stg;
copy into TEST_ANALYTICS.AIRLINES.airlines_stg from 
                                @TEST_ANALYTICS.AIRLINES.TEST_AIRLINES_BLOB_STG/Airlines_Data.csv.gz
                                            file_format = 'TEST_ANALYTICS.AIRLINES.AIRLINES_CSV_FORMAT',
                                            ON_ERROR = ABORT_STATEMENT ,
                                            force = FALSE;
                                            
[2024-02-29T10:57:21.479+0000] {base.py:83} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-02-29T10:57:21.581+0000] {base.py:83} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-02-29T10:57:21.582+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.11.8, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-02-29T10:57:21.583+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-02-29T10:57:22.940+0000] {cursor.py:1032} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-02-29T10:57:23.147+0000] {cursor.py:1045} INFO - query execution done
[2024-02-29T10:57:23.154+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-29T10:57:23.165+0000] {sql.py:457} INFO - Running statement: Truncat  table TEST_ANALYTICS.AIRLINES.airlines_stg;, parameters: None
[2024-02-29T10:57:23.168+0000] {cursor.py:1032} INFO - query: [Truncat  table TEST_ANALYTICS.AIRLINES.airlines_stg;]
[2024-02-29T10:57:23.281+0000] {cursor.py:1045} INFO - query execution done
[2024-02-29T10:57:23.287+0000] {connection.py:734} INFO - closed
[2024-02-29T10:57:23.344+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-02-29T10:57:23.415+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 390, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.11/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01b2ac51-0001-1956-0000-000393fa9009: SQL compilation error:
syntax error line 1 at position 0 unexpected 'Truncat'.
[2024-02-29T10:57:23.488+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=AIRLINES_ETL_PIPELINE, task_id=blob_to_snowflake_stg, execution_date=20240229T105707, start_date=20240229T105719, end_date=20240229T105723
[2024-02-29T10:57:23.705+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 112 for task blob_to_snowflake_stg (001003 (42000): 01b2ac51-0001-1956-0000-000393fa9009: SQL compilation error:
syntax error line 1 at position 0 unexpected 'Truncat'.; 1060)
[2024-02-29T10:57:23.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-29T10:57:23.816+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
[2024-02-29T10:57:23.853+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
